### PR TITLE
Update baselines to not include initialization time

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Current perf:

pardijk
```
-- Performance Table ---
 Scene Name      | 2               | 4               | 8               
-----------------------------------------------------------------------
 bench-64        | 8.8e-05         | 0.000187        | 0.000387        
 bench-256       | 0.000359        | 0.000677        | 0.000395        
 bench-1024      | 0.001439        | 0.001488        | 0.001765        
 bench-4096      | 0.015637        | 0.010914        | 0.010777        
 bench-8191      | 0.055649        | 0.03562         | 0.029518        

-- Speedup Table ---
 Scene Name      | 2               | 4               | 8               
-----------------------------------------------------------------------
 bench-64        | 0.272727        | 0.128342        | 0.062016        
 bench-256       | 0.615599        | 0.326440        | 0.559494        
 bench-1024      | 1.963864        | 1.899194        | 1.601133        
 bench-4096      | 2.173435        | 3.113982        | 3.153568        
 bench-8191      | 2.694388        | 4.209433        | 5.079612
```

pardijkMdlist
```
-- Performance Table ---
 Scene Name      | 4               | 8               
-----------------------------------------------------
 bench-64        | 0.000116        | 0.000193        
 bench-256       | 0.000257        | 0.000374        
 bench-1024      | 0.001471        | 0.00591         
 bench-4096      | 0.011027        | 0.026796        
 bench-8191      | 0.035399        | 0.044841        

-- Speedup Table ---
 Scene Name      | 4               | 8               
-----------------------------------------------------
 bench-64        | 0.206897        | 0.124352        
 bench-256       | 0.859922        | 0.590909        
 bench-1024      | 2.600952        | 0.647377        
 bench-4096      | 3.988936        | 1.641514        
 bench-8191      | 4.235713        | 3.343815        
average speedup: 1.8240386805037265
```

**Comment by JunTaoLuo** [comment]
After removing warning:

```
 Scene Name      | 2               | 4               | 8               
-----------------------------------------------------------------------
 bench-64        | 9.3e-05         | 0.000145        | 0.000241        
 bench-256       | 0.000481        | 0.000394        | 0.000663        
 bench-1024      | 0.002044        | 0.001297        | 0.001019        
 bench-4096      | 0.018798        | 0.01044         | 0.00682         
 bench-8191      | 0.116867        | 0.034208        | 0.021115        
-- Speedup Table ---
 Scene Name      | 2               | 4               | 8               
-----------------------------------------------------------------------
 bench-64        | 0.258065        | 0.165517        | 0.099585        
 bench-256       | 0.459459        | 0.560914        | 0.333333        
 bench-1024      | 1.382583        | 2.178874        | 2.773307        
 bench-4096      | 1.807958        | 3.255364        | 4.983284        
 bench-8191      | 1.282997        | 4.383185        | 7.101113  
```

**Comment by yuminc1234** [comment]
pardijk
```
-- Performance Table ---
 Scene Name      | 4               | 8               
-----------------------------------------------------
 bench-64        | 0.000135        | 0.000203        
 bench-256       | 0.000342        | 0.000558        
 bench-1024      | 0.001425        | 0.001695        
 bench-4096      | 0.014005        | 0.010511        
 bench-8191      | 0.038841        | 0.028875        

-- Speedup Table ---
 Scene Name      | 4               | 8               
-----------------------------------------------------
 bench-64        | 0.177778        | 0.118227        
 bench-256       | 0.646199        | 0.396057        
 bench-1024      | 2.684912        | 2.257227        
 bench-4096      | 3.140735        | 4.184759        
 bench-8191      | 3.860354        | 5.192727        
average speedup: 2.2658975274531623
```

**Comment by JunTaoLuo** [comment]
PSC results:

MDList
```
-- Performance Table ---
-- Performance Table ---
 Scene Name  | 2           | 4           | 8           | 16          | 32          | 64
---------------------------------------------------------------------------------------------
 bench-64    | 0.000495    | 0.000597    | 0.000888    | 0.001161    | 0.007756    | 0.015296
 bench-256   | 0.001165    | 0.00097     | 0.001062    | 0.00135     | 0.00224     | 0.014903
 bench-1024  | 0.007018    | 0.004686    | 0.003832    | 0.003232    | 0.005098    | 0.020723
 bench-4096  | 0.05107     | 0.031908    | 0.02054     | 0.014684    | 0.011624    | 0.01802
 bench-8191  | 0.152874    | 0.087819    | 0.051448    | 0.03851     | 0.027803    | 0.028424

-- Speedup Table ---
 Scene Name  | 2           | 4           | 8           | 16          | 32          | 64
---------------------------------------------------------------------------------------------
 bench-64    | 0.040404    | 0.033501    | 0.022523    | 0.017227    | 0.002579    | 0.001308
 bench-256   | 0.279828    | 0.336082    | 0.306968    | 0.241481    | 0.145536    | 0.021875
 bench-1024  | 0.595896    | 0.892446    | 1.091336    | 1.293936    | 0.820322    | 0.201805
 bench-4096  | 1.215019    | 1.944685    | 3.020983    | 4.225756    | 5.338180    | 3.443452
 bench-8191  | 1.695324    | 2.951195    | 5.037533    | 6.729966    | 9.321692    | 9.118034
```

GLock
```
 Scene Name  | 2           | 4           | 8           | 16          | 32          | 64
---------------------------------------------------------------------------------------------
 bench-64    | 0.00038     | 0.000424    | 0.000798    | 0.000998    | 0.0029      | 0.015268
 bench-256   | 0.000739    | 0.000841    | 0.001232    | 0.001479    | 0.005017    | 0.014617
 bench-1024  | 0.004475    | 0.004144    | 0.00528     | 0.006038    | 0.006879    | 0.025166
 bench-4096  | 0.037754    | 0.028192    | 0.023348    | 0.025711    | 0.028318    | 0.029211
 bench-8191  | 0.118094    | 0.08308     | 0.066503    | 0.054562    | 0.052378    | 0.050342

-- Speedup Table ---
 Scene Name  | 2           | 4           | 8           | 16          | 32          | 64
---------------------------------------------------------------------------------------------
 bench-64    | 0.052632    | 0.047170    | 0.025063    | 0.020040    | 0.006897    | 0.001310
 bench-256   | 0.441137    | 0.387634    | 0.264610    | 0.220419    | 0.064979    | 0.022303
 bench-1024  | 0.934525    | 1.009170    | 0.792045    | 0.692613    | 0.607937    | 0.166177
 bench-4096  | 1.643561    | 2.201014    | 2.657658    | 2.413403    | 2.191221    | 2.124234
 bench-8191  | 2.194616    | 3.119535    | 3.897132    | 4.750027    | 4.948089    | 5.148206 
```

**Pull request merged**
